# Generated by Django 5.2.1 on 2025-05-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('date_achat', models.DateField()),
                ('nb_places', models.IntegerField()),
                ('description', models.TextField()),
                ('longueur', models.FloatField()),
                ('climatisation', models.BooleanField()),
            ],
        ),
    ]
